# see https://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "2.7"
  - "3.7"
before_install:
  ./run -i
  ./run -s&
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
