!!python/object:gremlin.remote.Server
alias: g
helpUrl: http://wiki.bitplan.com/index.php/Gremlin_python#Connecting_to_Gremlin_enabled_graph_databases
host: localhost
name: OrientDB
password: rootpwd
port: 8182
username: root
serializer: { className: org.apache.tinkerpop.gremlin. driver.ser.GraphSONMessageSerializerV1d0, config: { serializeResultToString: true }}
