!!python/object:gremlin.remote.Server
alias: g
helpUrl: http://wiki.bitplan.com/index.php/Gremlin_python#Connecting_to_Gremlin_enabled_graph_databases
host: localhost
name: TinkerGraph
password: null
port: 8182
username: null
