#!/bin/bash
# WF 2022-01-21

install() {
  pip install .
}

run_server() {
  docker stop gremlin-server
  docker rm gremlin-server
  nohup scripts/run -sd&
}

wait_for_server() {
  local l_wait_time="$1"
  echo "waiting up to $l_wait_time secs for server"
  while [ $l_wait_time -gt 1 ]
  do
    sleep 1
    grep "Channel started at port 8182" nohup.out
    if [ $? -eq 0 ]
    then
      break
    fi
    l_wait_time=$((l_wait_time-1))
    echo "$l_wait_time secs left ..."
  done
}
install
run_server
wait_for_server 10

scripts/test
