name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8','3.9','3.10','3.11']
    steps:
     - uses: actions/checkout@v3
     - name: Setup Graphviz
       uses: ts-graphviz/setup-graphviz@v1
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v4
       with:
        python-version: ${{ matrix.python-version }}
     - name: Install dependencies and test
       run: |
        scripts/installAndTest
